// Code generated by assets. DO NOT EDIT.

package main

import "fmt"

func loadtemplate(name string) ([]byte, error) {
	switch name {
	case "markdown.tmpl":
		return []byte(`# Resources
{{ $references := .References -}}
{{ range $_, $sec :=.Sections -}}
## {{ $sec.Name }}
{{ range $_, $ref := $references -}}
{{ if eq $ref.Section $sec.ID -}}
* [{{ $ref.Title }}]({{ $ref.URL }})
    {{- if $ref.Author }} {{ $ref.Author }}.{{- end}}
    {{- if $ref.Note }} _Note:_ {{ $ref.Note }}{{- end}}
{{ end -}}
{{- end -}}
{{- end -}}
`), nil

	default:
		return nil, fmt.Errorf("unknown asset %s", name)
	}
}
