// Code generated by command: go run asm.go -out fp25519.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Add25519(x *[32]byte, y *[32]byte)
TEXT ·Add25519(SB), NOSPLIT, $0-16
	MOVQ    x+0(FP), AX
	MOVQ    (AX), CX
	MOVQ    8(AX), DX
	MOVQ    16(AX), BX
	MOVQ    24(AX), BP
	MOVQ    y+8(FP), SI
	MOVQ    (SI), DI
	MOVQ    8(SI), R8
	MOVQ    16(SI), R9
	MOVQ    24(SI), SI
	XORQ    R10, R10
	MOVQ    $0x00000026, R11
	ADDQ    DI, CX
	ADCXQ   R8, DX
	ADCXQ   R9, BX
	ADCXQ   SI, BP
	MOVQ    R10, SI
	CMOVQCS R11, SI
	ADDQ    SI, CX
	ADCXQ   R10, DX
	ADCXQ   R10, BX
	ADCXQ   R10, BP
	MOVQ    R10, SI
	CMOVQCS R11, SI
	ADCXQ   SI, CX
	MOVQ    CX, (AX)
	MOVQ    DX, 8(AX)
	MOVQ    BX, 16(AX)
	MOVQ    BP, 24(AX)
	RET
