// Code generated by wrap.go. DO NOT EDIT.

package z3

/*
#cgo LDFLAGS: -lz3
#include <z3.h>
*/
import "C"

// Not returns not(x).
// Wraps Z3_mk_not.
func (x *Bool) Not() *Bool {
	return &Bool{
		ctx: x.ctx,
		ast: C.Z3_mk_not(x.ctx, x.ast),
	}
}

// Iff returns x iff y.
// Wraps Z3_mk_iff.
func (x *Bool) Iff(y *Bool) *Bool {
	return &Bool{
		ctx: x.ctx,
		ast: C.Z3_mk_iff(x.ctx, x.ast, y.ast),
	}
}
