// Code generated by ec3. DO NOT EDIT.

package p256

import (
	"crypto/elliptic"
	"crypto/subtle"
	"math/big"
)

// References:
//
//	[msrecclibpaper]  Joppe W. Bos, Craig Costello, Patrick Longa and Michael Naehrig. Selecting
//	                  Elliptic Curves for Cryptography: An Efficiency and Security Analysis.
//	                  Cryptology ePrint Archive, Report 2014/130. 2014.
//	                  https://eprint.iacr.org/2014/130

// P256 returns a Curve which implements P-256.
func P256() elliptic.Curve { return p256 }

type curve struct{ *elliptic.CurveParams }

var p256 = curve{
	CurveParams: &elliptic.CurveParams{Name: "P-256"},
}

func init() {
	p256.P, _ = new(big.Int).SetString("115792089210356248762697446949407573530086143415290314195533631308867097853951", 10)
	p256.N, _ = new(big.Int).SetString("115792089210356248762697446949407573529996955224135760342422259061068512044369", 10)
	p256.B, _ = new(big.Int).SetString("5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b", 16)
	p256.Gx, _ = new(big.Int).SetString("6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296", 16)
	p256.Gy, _ = new(big.Int).SetString("4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5", 16)
	p256.BitSize = 256
}

// Add returns the sum of (x1,y1) and (x2,y2)
func (c curve) Add(x1, y1, x2, y2 *big.Int) (x, y *big.Int) {
	a1 := NewAffine(x1, y1)
	a2 := NewAffine(x2, y2)
	j1 := a1.Jacobian()
	j2 := a2.Jacobian()
	s := new(Jacobian)
	s.Add(j1, j2)
	return s.Affine().Coordinates()
}

// Double returns 2*(x1,y1)
func (c curve) Double(x1, y1 *big.Int) (x, y *big.Int) {
	a1 := NewAffine(x1, y1)
	j1 := a1.Jacobian()
	d := new(Jacobian)
	d.Double(j1)
	return d.Affine().Coordinates()
}

// ScalarMult returns k*(x1,y1) where k is a number in big-endian form.
func (c curve) ScalarMult(x1, y1 *big.Int, k []byte) (x, y *big.Int) {
	// Implementation follows [msrecclibpaper] Algorithm 1.

	// Scalar recoding window size.
	const w = 6

	// Convert point from affine.
	a := NewAffine(x1, y1)
	p := a.Jacobian()

	// Step 1: scalar validation.

	// TODO(mbm): exit if scalar is 0.

	var K scalar
	K.SetBytes(k)

	// Step 5: odd = k mod 2
	// Step 6: if odd = 0 then k = r − k
	even := K.ConvertToOdd()

	// Step 7: Recode k to (k_t, ..., k_0) using Algorithm 6.
	digits := K.FixedWindowRecode()

	// Step 4: Compute P[i] = (2i + 1)P for 0 ⩽ i < 2^{w−2}.
	var tbl table
	tbl.Precompute(p)

	// Step 8: Q = s_t * P[(|k_t| − 1)/2]
	var q, r Jacobian

	t := len(digits) - 1
	tbl.Lookup(&q, digits[t])

	// Step 9: for i = (t − 1) to 1
	for i := t - 1; i >= 1; i-- {
		// Step 14: Q = 2^{w−1}Q
		for j := 0; j < w-1; j++ {
			q.Double(&q)
		}

		// Step 15: Q = Q + s_i * P[(|k_i| − 1)/2]
		tbl.Lookup(&r, digits[i])
		q.Add(&q, &r)
	}

	// Step 18: Q = 2^{w−1}Q
	for j := 0; j < w-1; j++ {
		q.Double(&q)
	}

	// Step 19: Q = Q ⊕ s_0 * P[(|k_0| − 1)/2]
	tbl.Lookup(&r, digits[0])
	rp := r.Projective()
	qp := q.Projective()
	qp.CompleteAdd(qp, rp)

	// Step 20: if odd = 0 then Q = −Q
	qp.CNeg(even)

	// Step 21: Convert Q to affine coordinates (x, y).
	return qp.Affine().Coordinates()
}

// tablesize is the size of the lookup table used by ScalarMult.
const tablesize = 1 << (6 - 1)

// table is a lookup table used by ScalarMult.
type table [tablesize]Jacobian

// Precompute odd multiples of p.
func (t *table) Precompute(p *Jacobian) {
	t[0].Set(p)

	var _2p Jacobian
	_2p.Double(p)

	for i := 1; i < tablesize; i++ {
		t[i].Add(&t[i-1], &_2p)
	}
}

// Lookup an odd multiple from the table and store it in p. The provided digit
// may be negative, in which case p will be negated.
func (t *table) Lookup(p *Jacobian, digit int32) {
	idx := abs(digit) / 2
	for i := range t {
		p.CMov(&t[i], uint(subtle.ConstantTimeEq(int32(i), idx)))
	}
	p.CNeg(sign(digit))
}

// abs returns the absolute value of x.
func abs(x int32) int32 {
	mask := x >> 31
	return (x + mask) ^ mask
}

// sign returns the sign bit of x.
func sign(x int32) uint {
	return uint(x>>31) & 1
}
