// Code generated by ec3. DO NOT EDIT.

package p256

//go:noescape
func add(X1_ *Elt, X2_ *Elt, X3_ *Elt, Y1_ *Elt, Y2_ *Elt, Y3_ *Elt, Z1_ *Elt, Z2_ *Elt, Z3_ *Elt)

//go:noescape
func double(X1_ *Elt, X3_ *Elt, Y1_ *Elt, Y3_ *Elt, Z1_ *Elt, Z3_ *Elt)

//go:noescape
func completeadd(X1_ *Elt, X2_ *Elt, X3_ *Elt, Y1_ *Elt, Y2_ *Elt, Y3_ *Elt, Z1_ *Elt, Z2_ *Elt, Z3_ *Elt, b *Elt)
