// Code generated by ec3. DO NOT EDIT.

package p256

//go:noescape
func CMov(y *Elt, x *Elt, c uint)

//go:noescape
func Add(z *Elt, x *Elt, y *Elt)

//go:noescape
func Sub(z *Elt, x *Elt, y *Elt)

//go:noescape
func Mul(z *Elt, x *Elt, y *Elt)

//go:noescape
func Sqr(z *Elt, x *Elt)
