// Code generated by ec3. DO NOT EDIT.

#include "textflag.h"

// func Add(z *Elt, x *Elt, y *Elt)
TEXT ·Add(SB), NOSPLIT, $0-24
	MOVQ    z+0(FP), AX
	MOVQ    x+8(FP), CX
	MOVQ    y+16(FP), DX
	MOVQ    (CX), BX
	MOVQ    8(CX), BP
	MOVQ    16(CX), SI
	MOVQ    24(CX), CX
	MOVQ    (DX), DI
	MOVQ    8(DX), R8
	MOVQ    16(DX), R9
	MOVQ    24(DX), DX
	XORQ    R10, R10
	ADDQ    DI, BX
	ADCQ    R8, BP
	ADCQ    R9, SI
	ADCQ    DX, CX
	ADCQ    $0x00000000, R10
	MOVQ    BX, DX
	MOVQ    BP, DI
	MOVQ    SI, R8
	MOVQ    CX, R9
	SUBQ    p<>+0(SB), DX
	SBBQ    p<>+8(SB), DI
	SBBQ    p<>+16(SB), R8
	SBBQ    p<>+24(SB), R9
	SBBQ    $0x00000000, R10
	CMOVQCC DX, BX
	CMOVQCC DI, BP
	CMOVQCC R8, SI
	CMOVQCC R9, CX
	MOVQ    BX, (AX)
	MOVQ    BP, 8(AX)
	MOVQ    SI, 16(AX)
	MOVQ    CX, 24(AX)
	RET

DATA p<>+0(SB)/8, $0xffffffffffffffff
DATA p<>+8(SB)/8, $0x00000000ffffffff
DATA p<>+16(SB)/8, $0x0000000000000000
DATA p<>+24(SB)/8, $0xffffffff00000001
GLOBL p<>(SB), RODATA|NOPTR, $32

// func Sub(z *Elt, x *Elt, y *Elt)
TEXT ·Sub(SB), NOSPLIT, $0-24
	MOVQ    z+0(FP), AX
	MOVQ    x+8(FP), CX
	MOVQ    y+16(FP), DX
	MOVQ    (CX), BX
	MOVQ    8(CX), BP
	MOVQ    16(CX), SI
	MOVQ    24(CX), CX
	MOVQ    (DX), DI
	MOVQ    8(DX), R8
	MOVQ    16(DX), R9
	MOVQ    24(DX), DX
	XORQ    R10, R10
	SUBQ    DI, BX
	SBBQ    R8, BP
	SBBQ    R9, SI
	SBBQ    DX, CX
	SBBQ    $0x00000000, R10
	MOVQ    BX, DX
	MOVQ    BP, DI
	MOVQ    SI, R8
	MOVQ    CX, R9
	ADDQ    p<>+0(SB), DX
	ADCQ    p<>+8(SB), DI
	ADCQ    p<>+16(SB), R8
	ADCQ    p<>+24(SB), R9
	ANDQ    $0x00000001, R10
	CMOVQNE DX, BX
	CMOVQNE DI, BP
	CMOVQNE R8, SI
	CMOVQNE R9, CX
	MOVQ    BX, (AX)
	MOVQ    BP, 8(AX)
	MOVQ    SI, 16(AX)
	MOVQ    CX, 24(AX)
	RET

// func Mul(z *Elt, x *Elt, y *Elt)
TEXT ·Mul(SB), NOSPLIT, $64-24
	MOVQ z+0(FP), AX
	MOVQ x+8(FP), CX
	MOVQ y+16(FP), BX

	// y[0]
	MOVQ (BX), DX
	XORQ BP, BP

	// x[0] * y[0] -> z[0]
	MULXQ (CX), SI, DI

	// x[1] * y[0] -> z[1]
	MULXQ 8(CX), R8, R9
	ADCXQ R8, DI

	// x[2] * y[0] -> z[2]
	MULXQ 16(CX), R8, R10
	ADCXQ R8, R9

	// x[3] * y[0] -> z[3]
	MULXQ 24(CX), DX, R8
	ADCXQ DX, R10
	ADCXQ BP, R8
	MOVQ  SI, (SP)

	// y[1]
	MOVQ 8(BX), DX
	XORQ BP, BP

	// x[0] * y[1] -> z[1]
	MULXQ (CX), SI, R11
	ADCXQ SI, DI
	ADOXQ R11, R9

	// x[1] * y[1] -> z[2]
	MULXQ 8(CX), SI, R11
	ADCXQ SI, R9
	ADOXQ R11, R10

	// x[2] * y[1] -> z[3]
	MULXQ 16(CX), SI, R11
	ADCXQ SI, R10
	ADOXQ R11, R8

	// x[3] * y[1] -> z[4]
	MULXQ 24(CX), DX, SI
	ADCXQ DX, R8
	ADCXQ BP, SI
	ADOXQ BP, SI
	MOVQ  DI, 8(SP)

	// y[2]
	MOVQ 16(BX), DX
	XORQ BP, BP

	// x[0] * y[2] -> z[2]
	MULXQ (CX), DI, R11
	ADCXQ DI, R9
	ADOXQ R11, R10

	// x[1] * y[2] -> z[3]
	MULXQ 8(CX), DI, R11
	ADCXQ DI, R10
	ADOXQ R11, R8

	// x[2] * y[2] -> z[4]
	MULXQ 16(CX), DI, R11
	ADCXQ DI, R8
	ADOXQ R11, SI

	// x[3] * y[2] -> z[5]
	MULXQ 24(CX), DX, DI
	ADCXQ DX, SI
	ADCXQ BP, DI
	ADOXQ BP, DI
	MOVQ  R9, 16(SP)

	// y[3]
	MOVQ 24(BX), DX
	XORQ BP, BP

	// x[0] * y[3] -> z[3]
	MULXQ (CX), BX, R9
	ADCXQ BX, R10
	ADOXQ R9, R8

	// x[1] * y[3] -> z[4]
	MULXQ 8(CX), BX, R9
	ADCXQ BX, R8
	ADOXQ R9, SI

	// x[2] * y[3] -> z[5]
	MULXQ 16(CX), BX, R9
	ADCXQ BX, SI
	ADOXQ R9, DI

	// x[3] * y[3] -> z[6]
	MULXQ 24(CX), CX, DX
	ADCXQ CX, DI
	ADCXQ BP, DX
	ADOXQ BP, DX
	MOVQ  R10, 24(SP)
	MOVQ  R8, 32(SP)
	MOVQ  SI, 40(SP)
	MOVQ  DI, 48(SP)
	MOVQ  DX, 56(SP)

	// Reduction.
	XORQ    CX, CX
	MOVQ    (SP), BX
	MOVQ    8(SP), BP
	MOVQ    16(SP), SI
	MOVQ    24(SP), DI
	MOVQ    32(SP), R8
	MOVQ    BX, DX
	XORQ    R9, R9
	MULXQ   p<>+0(SB), R10, R11
	ADCXQ   R10, BX
	ADOXQ   R11, BP
	MULXQ   p<>+8(SB), BX, R10
	ADCXQ   BX, BP
	ADOXQ   R10, SI
	MULXQ   p<>+16(SB), BX, R10
	ADCXQ   BX, SI
	ADOXQ   R10, DI
	MULXQ   p<>+24(SB), DX, BX
	ADCXQ   DX, DI
	ADOXQ   BX, R8
	ADCXQ   CX, R8
	ADCXQ   CX, R9
	ADOXQ   CX, R9
	MOVQ    40(SP), BX
	MOVQ    BP, DX
	XORQ    R10, R10
	MULXQ   p<>+0(SB), R11, R12
	ADCXQ   R11, BP
	ADOXQ   R12, SI
	MULXQ   p<>+8(SB), BP, R11
	ADCXQ   BP, SI
	ADOXQ   R11, DI
	MULXQ   p<>+16(SB), BP, R11
	ADCXQ   BP, DI
	ADOXQ   R11, R8
	MULXQ   p<>+24(SB), DX, BP
	ADCXQ   DX, R8
	ADOXQ   BP, BX
	ADCXQ   R9, BX
	ADCXQ   CX, R10
	ADOXQ   CX, R10
	MOVQ    48(SP), BP
	MOVQ    SI, DX
	XORQ    R9, R9
	MULXQ   p<>+0(SB), R11, R12
	ADCXQ   R11, SI
	ADOXQ   R12, DI
	MULXQ   p<>+8(SB), SI, R11
	ADCXQ   SI, DI
	ADOXQ   R11, R8
	MULXQ   p<>+16(SB), SI, R11
	ADCXQ   SI, R8
	ADOXQ   R11, BX
	MULXQ   p<>+24(SB), DX, SI
	ADCXQ   DX, BX
	ADOXQ   SI, BP
	ADCXQ   R10, BP
	ADCXQ   CX, R9
	ADOXQ   CX, R9
	MOVQ    56(SP), SI
	MOVQ    DI, DX
	XORQ    R10, R10
	MULXQ   p<>+0(SB), R11, R12
	ADCXQ   R11, DI
	ADOXQ   R12, R8
	MULXQ   p<>+8(SB), DI, R11
	ADCXQ   DI, R8
	ADOXQ   R11, BX
	MULXQ   p<>+16(SB), DI, R11
	ADCXQ   DI, BX
	ADOXQ   R11, BP
	MULXQ   p<>+24(SB), DX, DI
	ADCXQ   DX, BP
	ADOXQ   DI, SI
	ADCXQ   R9, SI
	ADCXQ   CX, R10
	ADOXQ   CX, R10
	MOVQ    R8, CX
	MOVQ    BX, DX
	MOVQ    BP, DI
	MOVQ    SI, R9
	SUBQ    p<>+0(SB), CX
	SBBQ    p<>+8(SB), DX
	SBBQ    p<>+16(SB), DI
	SBBQ    p<>+24(SB), R9
	SBBQ    $0x00000000, R10
	CMOVQCC CX, R8
	CMOVQCC DX, BX
	CMOVQCC DI, BP
	CMOVQCC R9, SI
	MOVQ    R8, (AX)
	MOVQ    BX, 8(AX)
	MOVQ    BP, 16(AX)
	MOVQ    SI, 24(AX)
	RET
