// Code generated by ec3. DO NOT EDIT.

package p256

import (
	"crypto/rand"
	"math/big"
	mathrand "math/rand"
	"testing"
)

func RandScalar(t *testing.T) *big.Int {
	t.Helper()
	N := p256.Params().N
	for {
		k, err := rand.Int(rand.Reader, N)
		if err != nil {
			t.Fatal(err)
		}
		if k.Sign() == 0 {
			continue
		}
		return k
	}
}

func RandOddScalar(t *testing.T) *big.Int {
	t.Helper()
	k := RandScalar(t)
	N := p256.Params().N
	if k.Bit(0) == 0 {
		k.Neg(k).Mod(k, N)
	}
	return k
}

func TestScalarFixedWindowRecode(t *testing.T) {
	for trial := 0; trial < 128; trial++ {
		k := RandOddScalar(t)

		var K scalar
		K.SetIntRaw(k)
		digits := K.FixedWindowRecode()

		// Verify all digits are odd.
		for i, digit := range digits {
			if (digit & 1) != 1 {
				t.Fatalf("digit %d is not odd", i)
			}
		}

		// Confirm the sum is correct.
		x := new(big.Int)
		for i := len(digits) - 1; i >= 0; i-- {
			x.Lsh(x, 6-1)
			x.Add(x, big.NewInt(int64(digits[i])))
		}

		if k.Cmp(x) != 0 {
			t.Logf("     k = %x", k)
			t.Logf("digits = %d", digits)
			t.Logf("   got = %x", x)
			t.FailNow()
		}
	}
}

func TestScalarSubInt(t *testing.T) {
	for trial := 0; trial < 128; trial++ {
		x := RandScalar(t)
		v := mathrand.Int31n(64) - 32

		// Compute subtraction via scalar type.
		var k scalar
		k.SetIntRaw(x)
		k.SubInt32(v)
		got := k.IntRaw()

		// Compute expectation.
		expect := new(big.Int).Sub(x, new(big.Int).SetInt64(int64(v)))

		if got.Cmp(expect) != 0 {
			t.FailNow()
		}
	}
}

func TestScalarRsh(t *testing.T) {
	for trial := 0; trial < 128; trial++ {
		x := RandScalar(t)
		s := uint(1 + mathrand.Intn(63))

		// Compute shift via scalar type.
		var k scalar
		k.SetIntRaw(x)
		k.Rsh(s)
		got := k.IntRaw()

		// Compute expectation.
		expect := new(big.Int).Rsh(x, s)

		if got.Cmp(expect) != 0 {
			t.FailNow()
		}
	}
}
