// Code generated by ec3. DO NOT EDIT.

package p256

func scalarcmov(y *scalar, x *scalar, c uint)

func scalaradd(z *scalar, x *scalar, y *scalar)

func scalarsub(z *scalar, x *scalar, y *scalar)

func scalarmul(z *scalar, x *scalar, y *scalar)
