// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/mmcloughlin/ec3/efd/op3/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Program",
			pos:  position{line: 9, col: 1, offset: 34},
			expr: &actionExpr{
				pos: position{line: 9, col: 12, offset: 45},
				run: (*parser).callonProgram1,
				expr: &seqExpr{
					pos: position{line: 9, col: 12, offset: 45},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 9, col: 12, offset: 45},
							label: "as",
							expr: &zeroOrMoreExpr{
								pos: position{line: 9, col: 15, offset: 48},
								expr: &ruleRefExpr{
									pos:  position{line: 9, col: 15, offset: 48},
									name: "Assignment",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 9, col: 27, offset: 60},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Assignment",
			pos:  position{line: 19, col: 1, offset: 241},
			expr: &actionExpr{
				pos: position{line: 19, col: 15, offset: 255},
				run: (*parser).callonAssignment1,
				expr: &seqExpr{
					pos: position{line: 19, col: 15, offset: 255},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 19, col: 15, offset: 255},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 19, col: 17, offset: 257},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 19, col: 26, offset: 266},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 19, col: 28, offset: 268},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 19, col: 32, offset: 272},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 19, col: 34, offset: 274},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 19, col: 36, offset: 276},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 19, col: 47, offset: 287},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 19, col: 49, offset: 289},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 28, col: 1, offset: 414},
			expr: &choiceExpr{
				pos: position{line: 28, col: 15, offset: 428},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 28, col: 15, offset: 428},
						name: "Pow",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 21, offset: 434},
						name: "Inv",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 27, offset: 440},
						name: "Mul",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 33, offset: 446},
						name: "Neg",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 39, offset: 452},
						name: "Add",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 45, offset: 458},
						name: "Sub",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 51, offset: 464},
						name: "Cond",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 58, offset: 471},
						name: "Operand",
					},
				},
			},
		},
		{
			name: "Pow",
			pos:  position{line: 30, col: 1, offset: 480},
			expr: &actionExpr{
				pos: position{line: 30, col: 8, offset: 487},
				run: (*parser).callonPow1,
				expr: &seqExpr{
					pos: position{line: 30, col: 8, offset: 487},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 30, col: 8, offset: 487},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 10, offset: 489},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 19, offset: 498},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 30, col: 21, offset: 500},
							val:        "^",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 25, offset: 504},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 27, offset: 506},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 29, offset: 508},
								name: "Constant",
							},
						},
					},
				},
			},
		},
		{
			name: "Inv",
			pos:  position{line: 37, col: 1, offset: 611},
			expr: &actionExpr{
				pos: position{line: 37, col: 8, offset: 618},
				run: (*parser).callonInv1,
				expr: &seqExpr{
					pos: position{line: 37, col: 8, offset: 618},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 37, col: 8, offset: 618},
							val:        "1",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 37, col: 12, offset: 622},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 37, col: 14, offset: 624},
							val:        "/",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 37, col: 18, offset: 628},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 37, col: 20, offset: 630},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 37, col: 22, offset: 632},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "Mul",
			pos:  position{line: 43, col: 1, offset: 706},
			expr: &actionExpr{
				pos: position{line: 43, col: 8, offset: 713},
				run: (*parser).callonMul1,
				expr: &seqExpr{
					pos: position{line: 43, col: 8, offset: 713},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 43, col: 8, offset: 713},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 10, offset: 715},
								name: "Operand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 18, offset: 723},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 43, col: 20, offset: 725},
							val:        "*",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 24, offset: 729},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 43, col: 26, offset: 731},
							label: "y",
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 28, offset: 733},
								name: "Operand",
							},
						},
					},
				},
			},
		},
		{
			name: "Neg",
			pos:  position{line: 50, col: 1, offset: 833},
			expr: &actionExpr{
				pos: position{line: 50, col: 8, offset: 840},
				run: (*parser).callonNeg1,
				expr: &seqExpr{
					pos: position{line: 50, col: 8, offset: 840},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 50, col: 8, offset: 840},
							val:        "-",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 12, offset: 844},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 14, offset: 846},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 16, offset: 848},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "Add",
			pos:  position{line: 56, col: 1, offset: 922},
			expr: &actionExpr{
				pos: position{line: 56, col: 8, offset: 929},
				run: (*parser).callonAdd1,
				expr: &seqExpr{
					pos: position{line: 56, col: 8, offset: 929},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 56, col: 8, offset: 929},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 10, offset: 931},
								name: "Operand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 18, offset: 939},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 56, col: 20, offset: 941},
							val:        "+",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 24, offset: 945},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 26, offset: 947},
							label: "y",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 28, offset: 949},
								name: "Operand",
							},
						},
					},
				},
			},
		},
		{
			name: "Sub",
			pos:  position{line: 63, col: 1, offset: 1049},
			expr: &actionExpr{
				pos: position{line: 63, col: 8, offset: 1056},
				run: (*parser).callonSub1,
				expr: &seqExpr{
					pos: position{line: 63, col: 8, offset: 1056},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 63, col: 8, offset: 1056},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 10, offset: 1058},
								name: "Operand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 18, offset: 1066},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 63, col: 20, offset: 1068},
							val:        "-",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 24, offset: 1072},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 26, offset: 1074},
							label: "y",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 28, offset: 1076},
								name: "Operand",
							},
						},
					},
				},
			},
		},
		{
			name: "Cond",
			pos:  position{line: 70, col: 1, offset: 1176},
			expr: &actionExpr{
				pos: position{line: 70, col: 9, offset: 1184},
				run: (*parser).callonCond1,
				expr: &seqExpr{
					pos: position{line: 70, col: 9, offset: 1184},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 70, col: 9, offset: 1184},
							label: "x",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 11, offset: 1186},
								name: "Variable",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 20, offset: 1195},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 70, col: 22, offset: 1197},
							val:        "?",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 26, offset: 1201},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 28, offset: 1203},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 33, offset: 1208},
								name: "Variable",
							},
						},
					},
				},
			},
		},
		{
			name: "Operand",
			pos:  position{line: 79, col: 1, offset: 1327},
			expr: &actionExpr{
				pos: position{line: 79, col: 12, offset: 1338},
				run: (*parser).callonOperand1,
				expr: &labeledExpr{
					pos:   position{line: 79, col: 12, offset: 1338},
					label: "o",
					expr: &choiceExpr{
						pos: position{line: 79, col: 15, offset: 1341},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 79, col: 15, offset: 1341},
								name: "Variable",
							},
							&ruleRefExpr{
								pos:  position{line: 79, col: 26, offset: 1352},
								name: "Constant",
							},
						},
					},
				},
			},
		},
		{
			name: "Variable",
			pos:  position{line: 83, col: 1, offset: 1399},
			expr: &actionExpr{
				pos: position{line: 83, col: 13, offset: 1411},
				run: (*parser).callonVariable1,
				expr: &seqExpr{
					pos: position{line: 83, col: 13, offset: 1411},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 83, col: 13, offset: 1411},
							expr: &charClassMatcher{
								pos:        position{line: 83, col: 13, offset: 1411},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&charClassMatcher{
							pos:        position{line: 83, col: 20, offset: 1418},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 83, col: 29, offset: 1427},
							expr: &charClassMatcher{
								pos:        position{line: 83, col: 29, offset: 1427},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Constant",
			pos:  position{line: 87, col: 1, offset: 1482},
			expr: &actionExpr{
				pos: position{line: 87, col: 13, offset: 1494},
				run: (*parser).callonConstant1,
				expr: &labeledExpr{
					pos:   position{line: 87, col: 13, offset: 1494},
					label: "u",
					expr: &ruleRefExpr{
						pos:  position{line: 87, col: 15, offset: 1496},
						name: "Uint64Literal",
					},
				},
			},
		},
		{
			name: "Uint64Literal",
			pos:  position{line: 93, col: 1, offset: 1571},
			expr: &actionExpr{
				pos: position{line: 93, col: 18, offset: 1588},
				run: (*parser).callonUint64Literal1,
				expr: &choiceExpr{
					pos: position{line: 93, col: 19, offset: 1589},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 93, col: 19, offset: 1589},
							name: "HexUintLiteral",
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 36, offset: 1606},
							name: "OctalUintLiteral",
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 55, offset: 1625},
							name: "DecimalUintLiteral",
						},
					},
				},
			},
		},
		{
			name: "DecimalUintLiteral",
			pos:  position{line: 97, col: 1, offset: 1702},
			expr: &oneOrMoreExpr{
				pos: position{line: 97, col: 23, offset: 1724},
				expr: &charClassMatcher{
					pos:        position{line: 97, col: 23, offset: 1724},
					val:        "[0-9]",
					ranges:     []rune{'0', '9'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "HexUintLiteral",
			pos:  position{line: 99, col: 1, offset: 1732},
			expr: &seqExpr{
				pos: position{line: 99, col: 19, offset: 1750},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 99, col: 19, offset: 1750},
						val:        "0x",
						ignoreCase: false,
					},
					&oneOrMoreExpr{
						pos: position{line: 99, col: 24, offset: 1755},
						expr: &charClassMatcher{
							pos:        position{line: 99, col: 24, offset: 1755},
							val:        "[0-9a-fA-F]",
							ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "OctalUintLiteral",
			pos:  position{line: 101, col: 1, offset: 1769},
			expr: &seqExpr{
				pos: position{line: 101, col: 21, offset: 1789},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 101, col: 21, offset: 1789},
						val:        "0",
						ignoreCase: false,
					},
					&oneOrMoreExpr{
						pos: position{line: 101, col: 25, offset: 1793},
						expr: &charClassMatcher{
							pos:        position{line: 101, col: 25, offset: 1793},
							val:        "[0-7]",
							ranges:     []rune{'0', '7'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 105, col: 1, offset: 1823},
			expr: &oneOrMoreExpr{
				pos: position{line: 105, col: 7, offset: 1829},
				expr: &ruleRefExpr{
					pos:  position{line: 105, col: 7, offset: 1829},
					name: "Whitespace",
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 106, col: 1, offset: 1841},
			expr: &zeroOrMoreExpr{
				pos: position{line: 106, col: 6, offset: 1846},
				expr: &ruleRefExpr{
					pos:  position{line: 106, col: 6, offset: 1846},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 108, col: 1, offset: 1859},
			expr: &charClassMatcher{
				pos:        position{line: 108, col: 15, offset: 1873},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 109, col: 1, offset: 1881},
			expr: &litMatcher{
				pos:        position{line: 109, col: 8, offset: 1888},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 110, col: 1, offset: 1893},
			expr: &notExpr{
				pos: position{line: 110, col: 8, offset: 1900},
				expr: &anyMatcher{
					line: 110, col: 9, offset: 1901,
				},
			},
		},
	},
}

func (c *current) onProgram1(as interface{}) (interface{}, error) {
	p := &ast.Program{}
	for _, a := range as.([]interface{}) {
		p.Assignments = append(p.Assignments, a.(ast.Assignment))
	}
	return p, nil
}

func (p *parser) callonProgram1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProgram1(stack["as"])
}

func (c *current) onAssignment1(v, e interface{}) (interface{}, error) {
	return ast.Assignment{
		LHS: v.(ast.Variable),
		RHS: e.(ast.Expression),
	}, nil
}

func (p *parser) callonAssignment1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAssignment1(stack["v"], stack["e"])
}

func (c *current) onPow1(x, n interface{}) (interface{}, error) {
	return ast.Pow{
		X: x.(ast.Variable),
		N: n.(ast.Constant),
	}, nil
}

func (p *parser) callonPow1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPow1(stack["x"], stack["n"])
}

func (c *current) onInv1(x interface{}) (interface{}, error) {
	return ast.Inv{
		X: x.(ast.Variable),
	}, nil
}

func (p *parser) callonInv1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInv1(stack["x"])
}

func (c *current) onMul1(x, y interface{}) (interface{}, error) {
	return ast.Mul{
		X: x.(ast.Operand),
		Y: y.(ast.Operand),
	}, nil
}

func (p *parser) callonMul1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMul1(stack["x"], stack["y"])
}

func (c *current) onNeg1(x interface{}) (interface{}, error) {
	return ast.Neg{
		X: x.(ast.Variable),
	}, nil
}

func (p *parser) callonNeg1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNeg1(stack["x"])
}

func (c *current) onAdd1(x, y interface{}) (interface{}, error) {
	return ast.Add{
		X: x.(ast.Operand),
		Y: y.(ast.Operand),
	}, nil
}

func (p *parser) callonAdd1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdd1(stack["x"], stack["y"])
}

func (c *current) onSub1(x, y interface{}) (interface{}, error) {
	return ast.Sub{
		X: x.(ast.Operand),
		Y: y.(ast.Operand),
	}, nil
}

func (p *parser) callonSub1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSub1(stack["x"], stack["y"])
}

func (c *current) onCond1(x, cond interface{}) (interface{}, error) {
	return ast.Cond{
		X: x.(ast.Variable),
		C: cond.(ast.Variable),
	}, nil
}

func (p *parser) callonCond1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCond1(stack["x"], stack["cond"])
}

func (c *current) onOperand1(o interface{}) (interface{}, error) {
	return o.(ast.Operand), nil
}

func (p *parser) callonOperand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperand1(stack["o"])
}

func (c *current) onVariable1() (interface{}, error) {
	return ast.Variable(c.text), nil
}

func (p *parser) callonVariable1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVariable1()
}

func (c *current) onConstant1(u interface{}) (interface{}, error) {
	return ast.Constant(u.(uint64)), nil
}

func (p *parser) callonConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstant1(stack["u"])
}

func (c *current) onUint64Literal1() (interface{}, error) {
	return strconv.ParseUint(string(c.text), 0, 64)
}

func (p *parser) callonUint64Literal1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUint64Literal1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
